services:
  communityfund.webapi:
    image: communityfund.webapi
    build:
      context: .
      dockerfile: CommunityFund.WebApi/Dockerfile

  communityfund.webapi-1:
    image: communityfund.webapi-1
    build:
      context: .
      dockerfile: CommunityFund.WebApi/Dockerfile

  reportservice.webapi:
    image: reportservice.webapi-1
    build:
      context: .
      dockerfile: ReportService.WebApi/Dockerfile
