networks:
  app-tier:
    driver: bridge

name: communityfund
services:
  AuthService.WebApi:
    image: communityfund.webapi
    networks:
      - app-tier
    build:
      context: .
      dockerfile: AuthService.WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mysecretpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - $USERPROFILE\.aspnet\https:/https/

  CommunityFund.Postgres:
    image: postgres
    networks:
      - app-tier
    container_name: CommunityFund.Postgres
    hostname: CommunityFundPostgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=postgrespassword
